// Package sandbox confines the shell a test drives, using macOS Seatbelt
// (`sandbox-exec`) rather than a container runtime.
//
// The trade is deliberate. A container gives stronger isolation and a
// reproducible filesystem, but it makes the harness depend on a daemon
// being installed, running, and holding a pulled image — three things
// that fail independently and none of which have anything to do with the
// test being run. Seatbelt ships with the OS, starts in microseconds, and
// needs no daemon, at the cost of confining rather than replacing the
// host filesystem.
//
// The generated profile is a deny-list, not an allow-list: everything is
// permitted except writes outside a small set of scratch directories, and
// optionally the network. That is the honest shape for this tool — a
// deny-by-default profile that still lets a shell install packages and
// start services would end up allowing nearly everything anyway, while
// being far harder to read. It stops a test from scribbling over the
// user's home directory or system files; it is not a security boundary
// against hostile code.
package sandbox

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

// Program is the Seatbelt front-end. It is deprecated by Apple (and has
// been since 10.8) but remains present on every macOS release and is
// still what Chrome and other sandboxing tools drive. If it is ever
// removed, Available() is where that will surface.
const Program = "sandbox-exec"

// Config describes the sandbox to build around the shell.
type Config struct {
	// Enabled turns sandboxing on. Everything else is ignored when false.
	Enabled bool

	// WritablePaths are additional directories the shell may write to,
	// on top of DefaultWritablePaths.
	WritablePaths []string

	// DenyNetwork blocks all network access. Off by default: a test that
	// installs a package or curls a local service needs the network, and
	// that is the common case.
	DenyNetwork bool

	// ProfilePath is a hand-written .sb profile to use instead of the
	// generated one. When set, WritablePaths and DenyNetwork are ignored —
	// a custom profile is total, not a set of overrides.
	ProfilePath string
}

// DefaultWritablePaths returns the scratch directories a shell needs
// before it can do anything useful. TMPDIR matters as much as /tmp on
// macOS: it points into /var/folders, and without it `mktemp` fails.
func DefaultWritablePaths() []string {
	paths := []string{"/tmp", "/var/tmp"}
	if tmp := os.Getenv("TMPDIR"); tmp != "" {
		paths = append(paths, tmp)
	}
	return paths
}

// deviceAllowances are the character devices a shell writes to as a
// matter of course. /dev/null is the one that would otherwise break
// almost every real test — a bare `deny file-write*` turns every
// `>/dev/null` into "Operation not permitted".
//
// These are listed individually rather than allowing /dev wholesale,
// which would also expose raw disk devices.
var deviceAllowances = []string{
	`(literal "/dev/null")`,
	`(literal "/dev/zero")`,
	`(literal "/dev/random")`,
	`(literal "/dev/urandom")`,
	`(literal "/dev/stdout")`,
	`(literal "/dev/stderr")`,
	`(literal "/dev/tty")`,
	`(subpath "/dev/fd")`,
	`(regex #"^/dev/ttys[0-9]+$")`, // the PTY the harness itself allocates
}

// Available reports whether this machine can sandbox at all.
func Available() error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("sandboxing requires macOS (Seatbelt); this is %s — use -exec-prefix to wrap the shell in whatever sandbox your platform provides", runtime.GOOS)
	}
	if _, err := exec.LookPath(Program); err != nil {
		return fmt.Errorf("%s not found on PATH: %w", Program, err)
	}
	return nil
}

// Profile renders the SBPL profile text.
func (c Config) Profile() (string, error) {
	var b strings.Builder
	b.WriteString("(version 1)\n")
	b.WriteString(";; generated by slmtest — confines writes, not reads\n")
	b.WriteString("(allow default)\n\n")

	b.WriteString(";; Writes are denied except under explicit scratch paths.\n")
	b.WriteString("(deny file-write*)\n")

	paths := append(DefaultWritablePaths(), c.WritablePaths...)
	resolved, err := resolvePaths(paths)
	if err != nil {
		return "", err
	}
	if len(resolved) > 0 {
		b.WriteString("(allow file-write*\n")
		for _, p := range resolved {
			fmt.Fprintf(&b, "  (subpath %s)\n", quote(p))
		}
		b.WriteString(")\n")
	}

	b.WriteString("\n;; Devices a shell writes to as a matter of course.\n")
	b.WriteString("(allow file-write*\n")
	for _, d := range deviceAllowances {
		fmt.Fprintf(&b, "  %s\n", d)
	}
	b.WriteString(")\n")

	if c.DenyNetwork {
		b.WriteString("\n(deny network*)\n")
	}
	return b.String(), nil
}

// Argv returns the command prefix that runs a program under the sandbox.
// The shell is appended to it by the caller, so the result is an argv
// prefix in the same shape as -exec-prefix.
func (c Config) Argv() ([]string, error) {
	if !c.Enabled {
		return nil, nil
	}
	if err := Available(); err != nil {
		return nil, err
	}
	if c.ProfilePath != "" {
		if _, err := os.Stat(c.ProfilePath); err != nil {
			return nil, fmt.Errorf("sandbox profile: %w", err)
		}
		return []string{Program, "-f", c.ProfilePath}, nil
	}
	profile, err := c.Profile()
	if err != nil {
		return nil, err
	}
	// -p passes the profile inline, so there is no temporary file to
	// create, clean up, or race against.
	return []string{Program, "-p", profile}, nil
}

// resolvePaths makes each path absolute and resolves symlinks, dropping
// duplicates. Resolution is not optional on macOS: /tmp and /var/tmp are
// symlinks into /private, and Seatbelt matches on the resolved path — a
// profile naming "/tmp" silently permits nothing at all.
func resolvePaths(paths []string) ([]string, error) {
	seen := map[string]bool{}
	var out []string
	for _, p := range paths {
		if strings.TrimSpace(p) == "" {
			continue
		}
		abs, err := filepath.Abs(p)
		if err != nil {
			return nil, fmt.Errorf("sandbox writable path %q: %w", p, err)
		}
		// A path that doesn't exist yet is legitimate — a test may create
		// it — so fall back to the unresolved absolute form rather than
		// failing. Resolving the deepest existing ancestor keeps that case
		// correct when the missing part is under a symlinked root.
		resolved := resolveExisting(abs)
		if !seen[resolved] {
			seen[resolved] = true
			out = append(out, resolved)
		}
	}
	return out, nil
}

// resolveExisting resolves symlinks in the longest existing prefix of p
// and re-appends the rest.
func resolveExisting(p string) string {
	remainder := ""
	cur := p
	for {
		if r, err := filepath.EvalSymlinks(cur); err == nil {
			return filepath.Join(r, remainder)
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			return p // reached the root without finding anything that exists
		}
		remainder = filepath.Join(filepath.Base(cur), remainder)
		cur = parent
	}
}

// quote renders a Go string as an SBPL string literal.
func quote(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
